### Stage 1: Build ###
FROM node:20-alpine AS install_deps
WORKDIR /usr/src/app
COPY ["package*.json", "/usr/src/app/"]
RUN npm install

FROM node:20-alpine AS dev
WORKDIR /usr/src/app
COPY --from=install_deps /usr/src/app /usr/src/app/
COPY . .
RUN npm i -g @angular/cli@17
EXPOSE 4201
CMD ["npm", "run", "start"]
